### PR TITLE
Pi Pico Example added

### PR DESCRIPTION
**Pull request by Dave-Vallance**
Ok - Had a quick go at this... I have tried to follow the Artemis example as much as possible. I.e. same loop (without the LED), same expected logging output. Likewise, I have also copied your shell runner.

A readme was added for the pico specific stuff. 

Let me know if you want any changes!

### CODE REVIEW

**Comment by Dave-Vallance** [comment]
Ohh you might want to pay attention to the .gitignore file - I made some edits and the scope of those are not isolated to just my example (like ignoring all lock files)

**Comment by gauteh** [comment]
Thanks, this looks great! I think it should be listed along with example-artemis in the top level readme.

**Comment by Dave-Vallance** [comment]
Great! I can make a quick edit to that when I am next at my computer for more than a couple of minutes. (Probably tomorrow night or Monday).

**Comment by Dave-Vallance** [comment]
OK - updated - Let me know if you need anything else.

**Comment by gauteh** [comment]
Perfect, merging!

**Pull request merged**
