### PR TITLE
fix typo in pico-elf2uf2-defmt-wrapper.sh

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by gauteh** [comment]
Thanks, merging!

**Comment by brandonros** [comment]
@gauteh FYI I doubt it'll get merged but pico-elf2uf2-defmt-wrapper.sh "didn't work" for me on Mac OS X (just no output whatsoever, I verified UART was all set up + working correctly. If I did non-defmt stuff, like just send "Hello, world!" across it worked fine) so I came up with https://github.com/knurling-rs/defmt/pull/767

**Comment by gauteh** [comment]
socat and cat doesn't work so great on Mac, this snippet does the trick for our project: https://github.com/gauteh/sfy/blob/main/sfy-buoy/Makefile#L38 . Could maybe be added to the top level readme.

**Comment by gauteh** [comment]
Nice idea for defmt-print. There are a lot of serial port configs that should be added at some point. Since even socat doesn't manage to do this properly on all platforms, I am guessing it is a bit messy.

**Pull request merged**
